ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["11.1.0.0/16"]

operator:
  replicas: 1
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false

hubble:
  enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
  ui:
    enabled: true
  metrics:
    enabled: [dns, drop, tcp, flow, icmp, http]
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: false

bpf:
  masquerade: true

kubeProxyReplacement: true
k8sServiceHost: 10.0.0.10
k8sServicePort: 6443
