# Automatically generated by Terraform
# DO NOT edit manually. Changes must be made in modules/k8s_cluster/ansible_templates/inventory.ini

[control_plane]
%{ for name, node in nodes ~}
%{ if node.role == "control-plane" ~}
${node.ip} ansible_user=${node.user}
%{ endif ~}
%{ endfor ~}

[worker]
%{ for name, node in nodes ~}
%{ if node.role == "worker" ~}
${node.ip} ansible_user=${node.user}
%{ endif ~}
%{ endfor ~}

[k3s_cluster:children]
control_plane
worker

[all:vars]
ansible_ssh_private_key_file=${ssh_private_key_path}
